console.log("&&")
console.log(5>3 && 3==3)
console.log(3==2 && 5>3)
console.log(5>3 && 3==2)
console.log(3>5 && 3==2)
console.log('-----')
console.log("!&&")
console.log(!(5>3 && 3==3))
console.log(!(3==2 && 5>3))
console.log(!(5>3 && 3==2))
console.log(!(3>5 && 3==2))
console.log('-----')
console.log("||")
console.log(5>3 || 3==3)
console.log(3==2 || 5>3)
console.log(5>3 || 3==2)
console.log(3>5 || 3==2)
console.log('-----')
console.log("!||")
console.log(!(5>3 || 3==3))
console.log(!(3==2 || 5>3))
console.log(!(5>3 || 3==2))
console.log(!(3>5 || 3==2))
console.log('-----')
console.log("Outros exemplos com string e true/false")
console.log(3==3 && "Matheus"=="Matheus")
console.log("Matheus"=="Fábio" || false)
console.log(!(true &&  true))


