console.log(5>3)
console.log(3>5)
console.log('------')
console.log(3<=5)
console.log(5<=3)
console.log(3<=3)
console.log('------')
console.log('Bruno'!='Thales')
console.log('Bruno'!='Bruno Diferente')
console.log('Thales'=='Thales')